services:
  db: 
    image: postgres:16-alpine
    container_name: api_db
    environment:
      POSTGRES_DB: api_db 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: api_app
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/api_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
